<% require "dotenv"; Dotenv.load(".env") %>

service: empire-des-amis-infrastructure

image: tegbessou/empire-des-amis-infrastructure

servers:
  web:
     hosts:
        - 5.189.149.68
     options:
       user: root
       health-cmd: "curl -ksf -H 'Host: empire-des-amis.com' http://localhost/dashboard/ || exit 1"

proxy:
  ssl: true
  host: empire-des-amis.com
  forward_headers: true
  healthcheck:
    interval: 10
    path: /dashboard/
    timeout: 30

registry:
  username: tegbessou
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .
  dockerfile: ./docker/traefik/Dockerfile
  remote: ssh://root@5.189.149.68

ssh:
  user: root
  keys_only: false
  keys: [ "~/.ssh/id_rsa" ]

accessories:
  db:
    service: db
    image: tegbessou/empire-des-amis-database
    hosts:
      - 5.189.149.68
    port: "127.0.0.1:3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env:
      secret:
        - MARIADB_ROOT_PASSWORD
        - EDA_USER_PASSWORD
        - EDA_COUNTRY_PASSWORD
        - EDA_BOTTLE_INVENTORY_PASSWORD
        - EDA_TASTING_PASSWORD

  redis:
    service: redis
    image: redis:7.4-alpine
    hosts:
      - 5.189.149.68
    port: "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    service: rabbitmq
    image: rabbitmq:3
    hosts:
      - 5.189.149.68
    port: "127.0.0.1:5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env:
      secret:
        - RABBITMQ_DEFAULT_USER
        - RABBITMQ_DEFAULT_PASSWORD

  mongodb:
    service: mongodb
    image: mongo:8.0
    hosts:
      - 5.189.149.68
    port: "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  - /var/run/docker.sock:/var/run/docker.sock